services:
  - type: web
    name: p2p-file-transfer
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        fromEnvironment: true
      - key: SQLALCHEMY_DATABASE_URI
        fromEnvironment: true
      - key: UPLOAD_FOLDER
        value: "/opt/render/project/src/uploads"
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
